### PR TITLE
Toy model

### PR DESCRIPTION
**Pull request by ChayaSt**
See [README](https://github.com/ChayaSt/torsionfit_examples/blob/toy/synthetic_data/README.md)

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!

In addition to `t_equil`, did you store the statistical inefficiencies `g` for the production phases? And possibly also the effective number of equilibrium samples `Neff`? It would be useful to plot these too!

**Comment by ChayaSt** [comment]
I didn't store `g` but I did store `Neff` the MCMC chains so I can recalculate `g`. [Here](https://github.com/ChayaSt/torsionfit_examples/blob/toy/synthetic_data/convergence/t_equil_all.pdf) you can see the plot of `Neff`.

**Comment by ChayaSt** [comment]
[Here](https://github.com/ChayaSt/torsionfit_examples/blob/toy/synthetic_data/convergence/g_neff.pdf) is the plot of `g` and `N_eff` when the starting and true value are the same for all repeats.

[Here](https://github.com/ChayaSt/torsionfit_examples/blob/toy/synthetic_data/convergence/g_neff_rand.pdf) is the plot of `g` and `N_eff` when starting and true values are randomized. 

These are all for sigma.

**Comment by gregoryross** [comment]
Looks great. Very well documented!

**Pull request merged**
